version: '3'
services:

  restaurante-config-server:
    build:
      dockerfile: ./restaurante-config-server/restaurante-config-server.dockerfile
      context: .
    image: daniel/ws-restaurante-config-server
    container_name: ws-restaurante-config-server
    volumes:
      - /tmp
    ports:
      - "8888:8888"
    networks:
      - restaurante-network
    depends_on:
      - "mysql2"

  restaurante-eureka-server:
    build:
      dockerfile: ./restaurante-eureka-server/restaurante-eureka-server.dockerfile
      context: .
    image: daniel/ws-restaurante-eureka-server
    container_name: ws-restaurante-eureka-server
    ports:
      - "8761:8761"
    networks:
      - restaurante-network
    depends_on:
      - "restaurante-config-server"

  restaurante-api-gateway-zuul:
    build:
      dockerfile: ./restaurante-api-gateway-zuul/restaurante-api-gateway-zuul.dockerfile
      context: .
    image: daniel/ws-restaurante-api-gateway-zuul
    container_name: ws-restaurante-api-gateway-zuul
    ports:
      - "8765:8765"
    networks:
      - restaurante-network
    depends_on:
      - "restaurante-config-server"
      - "restaurante-eureka-server"

  restaurante-oauth:
    build:
      dockerfile: ./ws-restaurante-oauth/ws-restaurante-oauth.dockerfile
      context: .
    image: daniel/ws-restaurante-oauth
    container_name: ws-restaurante-oauth
    networks:
      - restaurante-network
    depends_on:
      - "restaurante-config-server"
      - "restaurante-api-gateway-zuul"

  restaurante-user:
    build:
      dockerfile: ./ws-restaurante-user/ws-restaurante-user.dockerfile
      context: .
    image: daniel/ws-restaurante-user
    container_name: ws-restaurante-user
    networks:
      - restaurante-network
    depends_on:
      - "restaurante-config-server"
      - "restaurante-api-gateway-zuul"

  restaurante-system:
    build:
      dockerfile: ./restaurante-system/restaurante-system.dockerfile
      context: .
    image: daniel/ws-restaurante-system
    container_name: ws-restaurante-system
    networks:
      - restaurante-network
    depends_on:
      - "restaurante-config-server"
      - "restaurante-api-gateway-zuul"

  mysql:
    image: mysql
    container_name: mysql-restaurante
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "toor"
    networks:
      - restaurante-network

  mysql2:
    image: mysql
    container_name: mysql-restaurante-user
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "toor"
    networks:
      - restaurante-network


networks:
  restaurante-network:
    driver: bridge
